name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - uses: pnpm/action-setup@2
        with:
          version: 7
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test:all
